"""added new fields to Item

Revision ID: d9717ade03ce
Revises: f8b31b3c9128
Create Date: 2023-08-15 07:51:15.547448

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'd9717ade03ce'
down_revision = 'f8b31b3c9128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
